name: Create release

on:
  workflow_call:
    inputs:
      REGISTRY:
        type: string
        required: false
        default: ghcr.io
      IMAGE_NAME:
        type: string
        required: true
      IMAGE_VERSION:
        type: string
        required: false
      DIRECTORY:
        type: string
        required: false
        default: "."

env:
  DOCKER_TAG: ""
  GIT_CONTEXT: ""

jobs:
  build-and-push:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Set DOCKER_TAG environment variable
        run: |
          if [ -n "${{ inputs.IMAGE_VERSION }}" ]; then
            echo "DOCKER_TAG=${{ inputs.IMAGE_VERSION }}" >> $GITHUB_ENV
          else
            VERSION=${{ github.ref_name }}
            echo "DOCKER_TAG=${VERSION#v}" >> $GITHUB_ENV
          fi
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64,linux/amd64
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Git context
        run: |
          GIT_CONTEXT="{{defaultContext}}"

          if [ -n "${{ inputs.DIRECTORY }}" ]; then
            GIT_CONTEXT="{{defaultContext}}:${{ inputs.DIRECTORY }}"
          fi

          echo "GIT_CONTEXT=${GIT_CONTEXT}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.GIT_CONTEXT }}
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
      - name: Create release
        uses: ncipollo/release-action@v1.16.0
        with:
          generateReleaseNotes: true
