name: Scan credentials

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  scan-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan secrets
        uses: trufflesecurity/trufflehog@main
