name: Create tag

on:
  workflow_call:
    inputs:
      semver:
        description: "The tag version it is going to be created. Please make sure version number starts with 'v' (for example: v1.0.0, v2.1.2, etc.)"
        required: true
        type: string
    secrets:
      ACTIONS_PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Verify semver
        run: |
          VALUE=${{ inputs.semver }}

          if [[ $VALUE =~ v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]
          then
            echo Semver \'$VALUE\' is valid
            exit 0
          fi

          echo Semver \'$VALUE\' is not valid
          exit 1
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # A custom token has to be used so this workflow can trigger the create-release workflow
          # see: https://github.com/orgs/community/discussions/27028#discussioncomment-3254360
          token: ${{ secrets.ACTIONS_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name "GitHub Actions bot"
      - run: git config --global user.email "<>"
      - run: git fetch --prune --unshallow --tags
      - run: git commit -m "${{ inputs.semver }}" --allow-empty
      - run: git tag -a -m "${{ inputs.semver }}" ${{ inputs.semver }}
      - run: git push --follow-tags
